# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN-MIF-CORE — runtime multi-language backend dispatch.
"""Runtime multi-language backend dispatch.

Exposes the fastest-measured backend ordering per compute kernel. The
source of truth is :file:`bench/dispatch.toml`, regenerated by
:file:`tools/update_dispatch.py` from the JSON summaries under
:file:`bench/results/`; see the dispatch convention in
:file:`bench/README.md` §Workflow.

Resolution order at first call:

1. The repository table :file:`bench/dispatch.toml` (development
   checkout — the source of truth).
2. The packaged snapshot :file:`scpn_mif_core/_dispatch_table.toml`
   shipped inside the wheel, kept byte-identical to the repository table
   by ``tools/update_dispatch.py`` and its ``--check`` drift gate. This
   is what a pip-installed user resolves, so the measured fastest-first
   ordering (and therefore the Rust dispatch) survives installation.

Public entry points:

* :func:`preferred_backend` — the single fastest backend for a kernel.
* :func:`available_backends` — the full ordered list (fastest first).
* :func:`is_rust_available` — whether the optional ``scpn_mif_core_rs``
  extension is importable.

The implementation is intentionally tiny and dependency-free; ``tomllib``
is the only external read.
"""

from __future__ import annotations

import tomllib
from importlib import resources
from importlib.util import find_spec
from pathlib import Path
from typing import Final

_REPO_ROOT: Final = Path(__file__).resolve().parents[2]
_DISPATCH_PATH: Final = _REPO_ROOT / "bench" / "dispatch.toml"
_PACKAGED_TABLE: Final = "_dispatch_table.toml"

_cache: dict[str, list[str]] | None = None


def _parse(raw: bytes) -> dict[str, list[str]]:
    """Parse dispatch TOML bytes into the kernel → ordered-backend map."""
    doc = tomllib.loads(raw.decode("utf-8"))
    return {str(k): [str(b) for b in v] for k, v in doc.get("kernels", {}).items()}


def _read_table_bytes() -> bytes | None:
    """Return the dispatch table bytes, repo file first, packaged snapshot second."""
    if _DISPATCH_PATH.is_file():
        return _DISPATCH_PATH.read_bytes()
    packaged = resources.files(__package__).joinpath(_PACKAGED_TABLE)
    if packaged.is_file():
        return packaged.read_bytes()
    return None


def _load() -> dict[str, list[str]]:
    """Read the dispatch table once and memoise it."""
    global _cache
    if _cache is None:
        raw = _read_table_bytes()
        _cache = {} if raw is None else _parse(raw)
    return _cache


def reload() -> None:
    """Discard the cache so the next call rereads ``bench/dispatch.toml``."""
    global _cache
    _cache = None


def available_backends(kernel: str) -> list[str]:
    """Return the ordered backend list for ``kernel`` (fastest measured first).

    Falls back to ``['python']`` when the kernel is not registered.
    """
    return list(_load().get(kernel, ["python"]))


def registered_kernels() -> list[str]:
    """Return the kernel names explicitly registered in the dispatch table."""
    return sorted(_load())


def preferred_backend(kernel: str) -> str:
    """Return the single fastest backend listed for ``kernel``."""
    return available_backends(kernel)[0]


def is_rust_available() -> bool:
    """Return ``True`` if the optional ``scpn_mif_core_rs`` extension is importable."""
    return find_spec("scpn_mif_core_rs") is not None
