# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN-MIF-CORE — runtime multi-language backend dispatch.
"""Runtime multi-language backend dispatch.

Reads :file:`bench/dispatch.toml` at first call and exposes the
fastest-measured backend ordering per compute kernel. The table is
regenerated by :file:`tools/update_dispatch.py` from the JSON summaries
under :file:`bench/results/`; see the dispatch convention in
:file:`bench/README.md` §Workflow.

Public entry points:

* :func:`preferred_backend` — the single fastest backend for a kernel.
* :func:`available_backends` — the full ordered list (fastest first).
* :func:`is_rust_available` — whether the optional ``scpn_mif_core_rs``
  extension is importable.

The implementation is intentionally tiny and dependency-free; ``tomllib``
is the only external read.
"""

from __future__ import annotations

import tomllib
from importlib.util import find_spec
from pathlib import Path
from typing import Final

_REPO_ROOT: Final = Path(__file__).resolve().parents[2]
_DISPATCH_PATH: Final = _REPO_ROOT / "bench" / "dispatch.toml"

_cache: dict[str, list[str]] | None = None


def _load() -> dict[str, list[str]]:
    """Read the dispatch table once and memoise it."""
    global _cache
    if _cache is None:
        if not _DISPATCH_PATH.is_file():
            _cache = {}
        else:
            with _DISPATCH_PATH.open("rb") as fh:
                doc = tomllib.load(fh)
            _cache = {str(k): [str(b) for b in v] for k, v in doc.get("kernels", {}).items()}
    return _cache


def reload() -> None:
    """Discard the cache so the next call rereads ``bench/dispatch.toml``."""
    global _cache
    _cache = None


def available_backends(kernel: str) -> list[str]:
    """Return the ordered backend list for ``kernel`` (fastest measured first).

    Falls back to ``['python']`` when the kernel is not registered.
    """
    return list(_load().get(kernel, ["python"]))


def registered_kernels() -> list[str]:
    """Return the kernel names explicitly registered in the dispatch table."""
    return sorted(_load())


def preferred_backend(kernel: str) -> str:
    """Return the single fastest backend listed for ``kernel``."""
    return available_backends(kernel)[0]


def is_rust_available() -> bool:
    """Return ``True`` if the optional ``scpn_mif_core_rs`` extension is importable."""
    return find_spec("scpn_mif_core_rs") is not None
